---
abstract: 'patterns for matching DNS domains and TLDs'
author:
  - 'Gavin Carr <gavin@openfusion.com.au>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-Common-domain
no_index:
  directory:
    - inc
    - t
requires:
  Domain::PublicSuffix: 0.09
  Net::Domain::TLD: 1.72
  Net::LibIDN: 0
  Regexp::Common: 0
  List::MoreUtils: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
